### ISSUE TITLE
Extension not loading

### ISSUE THREAD

**Issue by Thebloxers998** [cloudlink-omega/e2ee#3]
Like why

**Comment by MikeDev101** [comment]
If you provided the steps you performed to try loading the extension, maybe I would be able to assist you. I'm not a mind reader.

**Comment by Thebloxers998** [comment]
> If you provided the steps you performed to try loading the extension, maybe I would be able to assist you. I'm not a mind reader.
  - Basically, I downloaded the javascript file extension 
  - Then I went to custom extensions, and went to **Files**
So yea

**Comment by Thebloxers998** [comment]
And i did the usual

**Comment by MikeDev101** [comment]
> > If you provided the steps you performed to try loading the extension, maybe I would be able to assist you. I'm not a mind reader.
> 
>     * Basically, I downloaded the javascript file extension
> 
>     * Then I went to custom extensions, and went to **Files**
>       So yea

Did you make sure to check "Run unsandboxed"?

**Comment by Thebloxers998** [comment]
> > > If you provided the steps you performed to try loading the extension, maybe I would be able to assist you. I'm not a mind reader.
> > 
> > 
> > ```
> > * Basically, I downloaded the javascript file extension
> > 
> > * Then I went to custom extensions, and went to **Files**
> >   So yea
> > ```
> 
> Did you make sure to check "Run unsandboxed"?

Yep, I did

**Comment by MikeDev101** [comment]
found the issue. working on resolving it now.

**Comment by Thebloxers998** [comment]
ok 👍
